name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev, main]
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout le code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Setup Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444
        with:
          node-version: 24

      - name: Cache npm
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Installer les dépendances
        run: npm install

      - name: Linter
        run: npm run lint

      - name: Tests unitaires
        run: npm run test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@fd88b7d7ccbaefd23d8f36f73b59db7a3d246602
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Retire
        run: npx retire

      - name: Audit deps (prod)
        run: npm audit -R --environment production

      - name: Audit deps (dev)
        run: npm audit --environment development || true

      - name: Extraire la version du package.json
        id: pkg
        run: echo "version=$(jq -r .version package.json)" >> "$GITHUB_OUTPUT"

      - name: Préparer le nom de l'image (en minuscules)
        id: image
        run: |
          owner_lc=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "name=ghcr.io/$owner_lc/backend-node" >> "$GITHUB_OUTPUT"

      # Configurer Buildx pour le multi-arch
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      # Authentification à GHCR
      - name: Connexion à GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build multi-arch et push avec tags
      - name: Build et push multi-arch Docker image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.image.outputs.name }}:latest
            ${{ steps.image.outputs.name }}:${{ steps.pkg.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Vérifier les tags publiés
        run: |
          echo "Image pushed:"
          echo "${{ steps.image.outputs.name }}:latest"
          echo "${{ steps.image.outputs.name }}:${{ steps.pkg.outputs.version }}"
